import fs from 'fs'
import path from 'path'
import { UnifiedConfig } from './types.js'

function toToml(config: UnifiedConfig): string {
  const lines: string[] = ['# Generated by ai-bridge — do not edit directly.', '# Edit .ai/config.yaml and run `ai-bridge sync`', '']

  if (config.mcp_servers && Object.keys(config.mcp_servers).length > 0) {
    for (const [name, server] of Object.entries(config.mcp_servers)) {
      lines.push(`[mcp_servers.${name}]`)
      lines.push(`command = ${JSON.stringify(server.command)}`)
      if (server.env) {
        for (const [k, v] of Object.entries(server.env)) {
          lines.push(`env.${k} = ${JSON.stringify(v)}`)
        }
      }
      lines.push('')
    }
  }

  if (config.hooks && Object.keys(config.hooks).length > 0) {
    for (const [event, hookList] of Object.entries(config.hooks)) {
      for (const hook of hookList) {
        lines.push(`[[hooks.${event}]]`)
        lines.push(`command = ${JSON.stringify(hook.command)}`)
        if (hook.matcher) lines.push(`matcher = ${JSON.stringify(hook.matcher)}`)
        if (hook.timeout) lines.push(`timeout = ${hook.timeout}`)
        lines.push('')
      }
    }
  }

  return lines.join('\n')
}

export function generateCodexConfig(config: UnifiedConfig, outputDir: string): void {
  const content = toToml(config)
  const outPath = path.join(outputDir, '.codex', 'config.toml')
  fs.mkdirSync(path.dirname(outPath), { recursive: true })
  fs.writeFileSync(outPath, content)
}
